FROM zhayujie/chatgpt-on-wechat:debian

LABEL maintainer="foo@bar.com"
ARG TZ='Asia/Shanghai'

USER root

RUN apt-get update  \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        espeak  \
    && pip install --no-cache \
        baidu-aip \
        chardet \
        SpeechRecognition

# replace entrypoint
ADD ./entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

USER noroot

ENTRYPOINT ["/entrypoint.sh"]
